### ISSUE TITLE
打开本地报错

### ISSUE THREAD

**Issue by mcd316** [ZhongXiaoHong/superFileView#15]
invokeInstance -- exceptions:java.lang.NoSuchMethodException: onCallBackAction [class java.lang.Integer, class java.lang.Object, class java.lang.Object]
at java.lang.Class.getMethod(Class.java:1981)
at java.lang.Class.getMethod(Class.java:1637)
at com.tencent.tbs.reader.TbsReaderEventProxy.invokeInstance(Unknown Source)
at com.tencent.tbs.reader.TbsReaderEventProxy.doCallBackEvent(Unknown Source)
at com.tencent.tbs.reader.TbsReader.initReader(Unknown Source)
at com.tencent.tbs.reader.TbsReader.openFile(Unknown Source)
at java.lang.reflect.Method.invoke(Native Method)
at com.tencent.smtt.export.external.DexLoader.invokeMethod(Unknown Source)
at com.tencent.smtt.sdk.p.a(Unknown Source)
at com.tencent.smtt.sdk.TbsReaderView.openFile(Unknown Source)
at com.silang.superfileview.SuperFileView2.displayFile(SuperFileView2.java:80)
at com.silang.superfileview.FileDisplayActivity.getFilePathAndShowFile(FileDisplayActivity.java:72)

**Comment by mcd316** [comment]
已解决。楼主能问一下这个工具支持编辑吗？例如我能不能签名啊什么的？能的话是否可以告知如何实现！

**Comment by ZhongXiaoHong** [comment]
tbs不具备编辑功能

**Comment by treeseedm** [comment]
mcd316  这个问题如何解决的呢

**Comment by chenkexu** [comment]
@ZhongXiaoHong 大佬，上面那个问题怎么解决啊，我也遇到了。

**Comment by mcd316** [comment]
你们那边我不知道是什么原因，我这边很简单是路径错误了，本地没有找到这个文件。使用的as版本是2.3.3，grade 是3.3

**Comment by Moyuchen** [comment]
没有读写权限，在展示的时候需要申请读写权限
